export const TEST_DATA = [
  {
    object: "card",
    id: "c9f1fc97-00c0-492b-a4a3-b179afc2f95d",
    oracle_id: "8dedb9a7-0afa-4dff-b124-2344c170f11a",
    multiverse_ids: [],
    tcgplayer_id: 285789,
    cardmarket_id: 674640,
    name: "Abaddon the Despoiler",
    lang: "en",
    released_at: "2022-10-07",
    uri: "https://api.scryfall.com/cards/c9f1fc97-00c0-492b-a4a3-b179afc2f95d",
    scryfall_uri:
      "https://scryfall.com/card/40k/2/abaddon-the-despoiler?utm_source=api",
    layout: "normal",
    highres_image: true,
    image_status: "highres_scan",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/c/9/c9f1fc97-00c0-492b-a4a3-b179afc2f95d.jpg?1674058353",
      normal:
        "https://cards.scryfall.io/normal/front/c/9/c9f1fc97-00c0-492b-a4a3-b179afc2f95d.jpg?1674058353",
      large:
        "https://cards.scryfall.io/large/front/c/9/c9f1fc97-00c0-492b-a4a3-b179afc2f95d.jpg?1674058353",
      png: "https://cards.scryfall.io/png/front/c/9/c9f1fc97-00c0-492b-a4a3-b179afc2f95d.png?1674058353",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/c/9/c9f1fc97-00c0-492b-a4a3-b179afc2f95d.jpg?1674058353",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/c/9/c9f1fc97-00c0-492b-a4a3-b179afc2f95d.jpg?1674058353",
    },
    mana_cost: "{2}{U}{B}{R}",
    cmc: 5,
    type_line: "Legendary Creature — Astartes Warrior",
    oracle_text:
      "Trample\nMark of Chaos Ascendant — During your turn, spells you cast from your hand with mana value X or less have cascade, where X is the total amount of life your opponents have lost this turn.",
    power: "5",
    toughness: "5",
    colors: ["B", "R", "U"],
    color_identity: ["B", "R", "U"],
    keywords: ["Mark of Chaos Ascendant", "Trample"],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "not_legal",
      gladiator: "not_legal",
      pioneer: "not_legal",
      explorer: "not_legal",
      modern: "not_legal",
      legacy: "legal",
      pauper: "not_legal",
      vintage: "legal",
      penny: "not_legal",
      commander: "legal",
      oathbreaker: "legal",
      brawl: "not_legal",
      historicbrawl: "not_legal",
      alchemy: "not_legal",
      paupercommander: "not_legal",
      duel: "legal",
      oldschool: "not_legal",
      premodern: "not_legal",
      predh: "not_legal",
    },
    games: ["paper"],
    reserved: false,
    foil: true,
    nonfoil: false,
    finishes: ["foil"],
    oversized: false,
    promo: false,
    reprint: false,
    variation: false,
    set_id: "f35f5dd8-5b95-4f52-bbe7-1c62909a8d08",
    set: "40k",
    set_name: "Warhammer 40,000 Commander",
    set_type: "commander",
    set_uri:
      "https://api.scryfall.com/sets/f35f5dd8-5b95-4f52-bbe7-1c62909a8d08",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3A40k&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/40k?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/c9f1fc97-00c0-492b-a4a3-b179afc2f95d/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A8dedb9a7-0afa-4dff-b124-2344c170f11a&unique=prints",
    collector_number: "2",
    digital: false,
    rarity: "mythic",
    flavor_text: "Under his rule, there is but one creed: Chaos shall reign.",
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Johan Grenier",
    artist_ids: ["465e38b8-7eed-4d22-a6d2-d3603ee0c00b"],
    illustration_id: "6e907ae8-6447-4d42-8ac8-16fa30af6d44",
    border_color: "black",
    frame: "2015",
    frame_effects: ["legendary"],
    security_stamp: "triangle",
    full_art: false,
    textless: false,
    booster: false,
    story_spotlight: false,
    promo_types: ["surgefoil"],
    edhrec_rank: 6061,
    prices: {
      usd: null,
      usd_foil: "1.76",
      usd_etched: null,
      eur: null,
      eur_foil: "8.10",
      tix: null,
    },
    related_uris: {
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Abaddon+the+Despoiler&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Abaddon+the+Despoiler&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=Abaddon+the+Despoiler",
    },
    purchase_uris: {
      tcgplayer:
        "https://www.tcgplayer.com/product/285789?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      cardmarket:
        "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Abaddon+the+Despoiler&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
      cardhoarder:
        "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Abaddon+the+Despoiler&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
    },
  },
  {
    object: "card",
    id: "137b701e-6140-463e-84b5-58d8a728df40",
    oracle_id: "95db05eb-2c25-43f2-8e18-dfc64f490634",
    multiverse_ids: [29728],
    mtgo_id: 16909,
    mtgo_foil_id: 16910,
    tcgplayer_id: 9334,
    cardmarket_id: 2471,
    name: "Aboshan's Desire",
    lang: "en",
    released_at: "2001-10-01",
    uri: "https://api.scryfall.com/cards/137b701e-6140-463e-84b5-58d8a728df40",
    scryfall_uri:
      "https://scryfall.com/card/ody/59/aboshans-desire?utm_source=api",
    layout: "normal",
    highres_image: true,
    image_status: "highres_scan",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/1/3/137b701e-6140-463e-84b5-58d8a728df40.jpg?1562898738",
      normal:
        "https://cards.scryfall.io/normal/front/1/3/137b701e-6140-463e-84b5-58d8a728df40.jpg?1562898738",
      large:
        "https://cards.scryfall.io/large/front/1/3/137b701e-6140-463e-84b5-58d8a728df40.jpg?1562898738",
      png: "https://cards.scryfall.io/png/front/1/3/137b701e-6140-463e-84b5-58d8a728df40.png?1562898738",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/1/3/137b701e-6140-463e-84b5-58d8a728df40.jpg?1562898738",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/1/3/137b701e-6140-463e-84b5-58d8a728df40.jpg?1562898738",
    },
    mana_cost: "{U}",
    cmc: 1,
    type_line: "Enchantment — Aura",
    oracle_text:
      "Enchant creature\nEnchanted creature has flying.\nThreshold — Enchanted creature has shroud as long as seven or more cards are in your graveyard. (It can't be the target of spells or abilities.)",
    colors: ["U"],
    color_identity: ["U"],
    keywords: ["Enchant", "Threshold"],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "not_legal",
      gladiator: "not_legal",
      pioneer: "not_legal",
      explorer: "not_legal",
      modern: "not_legal",
      legacy: "legal",
      pauper: "legal",
      vintage: "legal",
      penny: "not_legal",
      commander: "legal",
      oathbreaker: "legal",
      brawl: "not_legal",
      historicbrawl: "not_legal",
      alchemy: "not_legal",
      paupercommander: "legal",
      duel: "legal",
      oldschool: "not_legal",
      premodern: "legal",
      predh: "legal",
    },
    games: ["paper", "mtgo"],
    reserved: false,
    foil: true,
    nonfoil: true,
    finishes: ["nonfoil", "foil"],
    oversized: false,
    promo: false,
    reprint: false,
    variation: false,
    set_id: "b0d90d2d-494a-4224-bfa0-36ce5ee281b1",
    set: "ody",
    set_name: "Odyssey",
    set_type: "expansion",
    set_uri:
      "https://api.scryfall.com/sets/b0d90d2d-494a-4224-bfa0-36ce5ee281b1",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3Aody&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/ody?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/137b701e-6140-463e-84b5-58d8a728df40/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A95db05eb-2c25-43f2-8e18-dfc64f490634&unique=prints",
    collector_number: "59",
    digital: false,
    rarity: "common",
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Ciruelo",
    artist_ids: ["1761c216-72b5-4a9b-afee-ad47a00fe1ad"],
    illustration_id: "79da9a59-a3ae-4d1a-a23c-1e4e096631f5",
    border_color: "black",
    frame: "1997",
    full_art: false,
    textless: false,
    booster: true,
    story_spotlight: false,
    edhrec_rank: 12665,
    penny_rank: 8622,
    prices: {
      usd: "0.26",
      usd_foil: "9.46",
      usd_etched: null,
      eur: "0.15",
      eur_foil: "0.50",
      tix: "0.04",
    },
    related_uris: {
      gatherer:
        "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=29728",
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Aboshan%27s+Desire&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Aboshan%27s+Desire&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=Aboshan%27s+Desire",
    },
    purchase_uris: {
      tcgplayer:
        "https://www.tcgplayer.com/product/9334?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      cardmarket:
        "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Aboshan%27s+Desire&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
      cardhoarder:
        "https://www.cardhoarder.com/cards/16909?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
    },
  },
  {
    object: "card",
    id: "d2fa85ea-f5d5-4be3-a874-ce246c3e4245",
    oracle_id: "18f34bfd-7675-49df-91ea-695c510cd3c3",
    multiverse_ids: [74187],
    mtgo_id: 22026,
    mtgo_foil_id: 22027,
    tcgplayer_id: 12393,
    cardmarket_id: 12621,
    name: "Adamaro, First to Desire",
    lang: "en",
    released_at: "2005-06-03",
    uri: "https://api.scryfall.com/cards/d2fa85ea-f5d5-4be3-a874-ce246c3e4245",
    scryfall_uri:
      "https://scryfall.com/card/sok/91/adamaro-first-to-desire?utm_source=api",
    layout: "normal",
    highres_image: true,
    image_status: "highres_scan",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/d/2/d2fa85ea-f5d5-4be3-a874-ce246c3e4245.jpg?1562496102",
      normal:
        "https://cards.scryfall.io/normal/front/d/2/d2fa85ea-f5d5-4be3-a874-ce246c3e4245.jpg?1562496102",
      large:
        "https://cards.scryfall.io/large/front/d/2/d2fa85ea-f5d5-4be3-a874-ce246c3e4245.jpg?1562496102",
      png: "https://cards.scryfall.io/png/front/d/2/d2fa85ea-f5d5-4be3-a874-ce246c3e4245.png?1562496102",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/d/2/d2fa85ea-f5d5-4be3-a874-ce246c3e4245.jpg?1562496102",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/d/2/d2fa85ea-f5d5-4be3-a874-ce246c3e4245.jpg?1562496102",
    },
    mana_cost: "{1}{R}{R}",
    cmc: 3,
    type_line: "Legendary Creature — Spirit",
    oracle_text:
      "Adamaro, First to Desire's power and toughness are each equal to the number of cards in the hand of the opponent with the most cards in hand.",
    power: "*",
    toughness: "*",
    colors: ["R"],
    color_identity: ["R"],
    keywords: [],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "not_legal",
      gladiator: "not_legal",
      pioneer: "not_legal",
      explorer: "not_legal",
      modern: "legal",
      legacy: "legal",
      pauper: "not_legal",
      vintage: "legal",
      penny: "legal",
      commander: "legal",
      oathbreaker: "legal",
      brawl: "not_legal",
      historicbrawl: "not_legal",
      alchemy: "not_legal",
      paupercommander: "not_legal",
      duel: "legal",
      oldschool: "not_legal",
      premodern: "not_legal",
      predh: "legal",
    },
    games: ["paper", "mtgo"],
    reserved: false,
    foil: true,
    nonfoil: true,
    finishes: ["nonfoil", "foil"],
    oversized: false,
    promo: false,
    reprint: false,
    variation: false,
    set_id: "4db16ad3-2b95-442f-bb6b-e9aa7fe7f769",
    set: "sok",
    set_name: "Saviors of Kamigawa",
    set_type: "expansion",
    set_uri:
      "https://api.scryfall.com/sets/4db16ad3-2b95-442f-bb6b-e9aa7fe7f769",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3Asok&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/sok?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/d2fa85ea-f5d5-4be3-a874-ce246c3e4245/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A18f34bfd-7675-49df-91ea-695c510cd3c3&unique=prints",
    collector_number: "91",
    digital: false,
    rarity: "rare",
    flavor_text:
      '"Beware Adamaro! In him all pain and anger is perfected."\n—Isao, Enlightened Bushi',
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Paolo Parente",
    artist_ids: ["d48dd097-720d-476a-8722-6a02854ae28b"],
    illustration_id: "6ebb00af-187a-4030-bf71-f0a77c394ae5",
    border_color: "black",
    frame: "2003",
    full_art: false,
    textless: false,
    booster: true,
    story_spotlight: false,
    edhrec_rank: 14580,
    penny_rank: 13389,
    prices: {
      usd: "0.87",
      usd_foil: "10.31",
      usd_etched: null,
      eur: "0.24",
      eur_foil: "7.00",
      tix: "0.01",
    },
    related_uris: {
      gatherer:
        "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74187",
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Adamaro%2C+First+to+Desire&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Adamaro%2C+First+to+Desire&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=Adamaro%2C+First+to+Desire",
    },
    purchase_uris: {
      tcgplayer:
        "https://www.tcgplayer.com/product/12393?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      cardmarket:
        "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Adamaro%2C+First+to+Desire&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
      cardhoarder:
        "https://www.cardhoarder.com/cards/22026?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
    },
  },
  {
    object: "card",
    id: "7673def9-9f27-4382-b65b-ec616fae1768",
    oracle_id: "714d8392-428d-4438-b8fb-4d0cc833cab0",
    multiverse_ids: [],
    arena_id: 77360,
    name: "A-Dungeon Descent",
    lang: "en",
    released_at: "2021-07-23",
    uri: "https://api.scryfall.com/cards/7673def9-9f27-4382-b65b-ec616fae1768",
    scryfall_uri:
      "https://scryfall.com/card/afr/A-255/a-dungeon-descent?utm_source=api",
    layout: "normal",
    highres_image: false,
    image_status: "lowres",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/7/6/7673def9-9f27-4382-b65b-ec616fae1768.jpg?1681158581",
      normal:
        "https://cards.scryfall.io/normal/front/7/6/7673def9-9f27-4382-b65b-ec616fae1768.jpg?1681158581",
      large:
        "https://cards.scryfall.io/large/front/7/6/7673def9-9f27-4382-b65b-ec616fae1768.jpg?1681158581",
      png: "https://cards.scryfall.io/png/front/7/6/7673def9-9f27-4382-b65b-ec616fae1768.png?1681158581",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/7/6/7673def9-9f27-4382-b65b-ec616fae1768.jpg?1681158581",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/7/6/7673def9-9f27-4382-b65b-ec616fae1768.jpg?1681158581",
    },
    mana_cost: "",
    cmc: 0,
    type_line: "Land",
    oracle_text:
      "{T}: Add {C}.\n{1}, {T}, Tap an untapped legendary creature you control: Venture into the dungeon. Activate only as a sorcery.",
    colors: [],
    color_identity: [],
    keywords: ["Venture into the dungeon"],
    produced_mana: ["C"],
    all_parts: [
      {
        object: "related_card",
        id: "7673def9-9f27-4382-b65b-ec616fae1768",
        component: "combo_piece",
        name: "A-Dungeon Descent",
        type_line: "Land",
        uri: "https://api.scryfall.com/cards/7673def9-9f27-4382-b65b-ec616fae1768",
      },
      {
        object: "related_card",
        id: "b9c7b02d-ac45-45b1-9f1b-2dbd2b5c3cdc",
        component: "combo_piece",
        name: "Dungeon Descent",
        type_line: "Land",
        uri: "https://api.scryfall.com/cards/b9c7b02d-ac45-45b1-9f1b-2dbd2b5c3cdc",
      },
    ],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "legal",
      gladiator: "not_legal",
      pioneer: "not_legal",
      explorer: "not_legal",
      modern: "not_legal",
      legacy: "not_legal",
      pauper: "not_legal",
      vintage: "not_legal",
      penny: "not_legal",
      commander: "not_legal",
      oathbreaker: "not_legal",
      brawl: "not_legal",
      historicbrawl: "legal",
      alchemy: "not_legal",
      paupercommander: "not_legal",
      duel: "not_legal",
      oldschool: "not_legal",
      premodern: "not_legal",
      predh: "not_legal",
    },
    games: ["arena"],
    reserved: false,
    foil: false,
    nonfoil: true,
    finishes: ["nonfoil"],
    oversized: false,
    promo: false,
    reprint: false,
    variation: false,
    set_id: "e1ef87ba-ba92-4573-817f-543b996d2851",
    set: "afr",
    set_name: "Adventures in the Forgotten Realms",
    set_type: "expansion",
    set_uri:
      "https://api.scryfall.com/sets/e1ef87ba-ba92-4573-817f-543b996d2851",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3Aafr&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/afr?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/7673def9-9f27-4382-b65b-ec616fae1768/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A714d8392-428d-4438-b8fb-4d0cc833cab0&unique=prints",
    collector_number: "A-255",
    digital: true,
    rarity: "rare",
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Kasia 'Kafis' Zielińska",
    artist_ids: ["a662cb71-4770-4b49-8b03-2cf8497049a7"],
    illustration_id: "d6eb7173-ebde-49c3-81dd-5fdd240813c0",
    border_color: "black",
    frame: "2015",
    security_stamp: "arena",
    full_art: false,
    textless: false,
    booster: false,
    story_spotlight: false,
    promo_types: ["rebalanced", "alchemy"],
    prices: {
      usd: null,
      usd_foil: null,
      usd_etched: null,
      eur: null,
      eur_foil: null,
      tix: null,
    },
    related_uris: {
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=A-Dungeon+Descent&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=A-Dungeon+Descent&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=A-Dungeon+Descent",
    },
  },
  {
    object: "card",
    id: "a2c044c0-3625-4bdf-9445-b462394cecae",
    oracle_id: "52adc761-1a0a-43d1-a706-41a92bb7880c",
    multiverse_ids: [262675, 262698],
    mtgo_id: 43329,
    mtgo_foil_id: 43330,
    tcgplayer_id: 57632,
    cardmarket_id: 252485,
    name: "Afflicted Deserter // Werewolf Ransacker",
    lang: "en",
    released_at: "2012-02-03",
    uri: "https://api.scryfall.com/cards/a2c044c0-3625-4bdf-9445-b462394cecae",
    scryfall_uri:
      "https://scryfall.com/card/dka/81/afflicted-deserter-werewolf-ransacker?utm_source=api",
    layout: "transform",
    highres_image: true,
    image_status: "highres_scan",
    cmc: 4,
    type_line: "Creature — Human Werewolf // Creature — Werewolf",
    color_identity: ["R"],
    keywords: ["Transform"],
    card_faces: [
      {
        object: "card_face",
        name: "Afflicted Deserter",
        mana_cost: "{3}{R}",
        type_line: "Creature — Human Werewolf",
        oracle_text:
          "At the beginning of each upkeep, if no spells were cast last turn, transform Afflicted Deserter.",
        colors: ["R"],
        power: "3",
        toughness: "2",
        flavor_text:
          "The rising of the first full moon eliminated any doubt as to the horrible truth lurking within.",
        artist: "David Palumbo",
        artist_id: "04ce1c75-e30c-4b7a-8cb0-b53e4ecc2f39",
        illustration_id: "0d3b25e6-5cd0-471c-be67-c9a22e79cc09",
        image_uris: {
          small:
            "https://cards.scryfall.io/small/front/a/2/a2c044c0-3625-4bdf-9445-b462394cecae.jpg?1581395071",
          normal:
            "https://cards.scryfall.io/normal/front/a/2/a2c044c0-3625-4bdf-9445-b462394cecae.jpg?1581395071",
          large:
            "https://cards.scryfall.io/large/front/a/2/a2c044c0-3625-4bdf-9445-b462394cecae.jpg?1581395071",
          png: "https://cards.scryfall.io/png/front/a/2/a2c044c0-3625-4bdf-9445-b462394cecae.png?1581395071",
          art_crop:
            "https://cards.scryfall.io/art_crop/front/a/2/a2c044c0-3625-4bdf-9445-b462394cecae.jpg?1581395071",
          border_crop:
            "https://cards.scryfall.io/border_crop/front/a/2/a2c044c0-3625-4bdf-9445-b462394cecae.jpg?1581395071",
        },
      },
      {
        object: "card_face",
        name: "Werewolf Ransacker",
        flavor_name: "",
        mana_cost: "",
        type_line: "Creature — Werewolf",
        oracle_text:
          "Whenever this creature transforms into Werewolf Ransacker, you may destroy target artifact. If that artifact is put into a graveyard this way, Werewolf Ransacker deals 3 damage to that artifact's controller.\nAt the beginning of each upkeep, if a player cast two or more spells last turn, transform Werewolf Ransacker.",
        colors: ["R"],
        color_indicator: ["R"],
        power: "5",
        toughness: "4",
        artist: "David Palumbo",
        artist_id: "04ce1c75-e30c-4b7a-8cb0-b53e4ecc2f39",
        illustration_id: "ade4c37e-4fc2-4a72-82af-00ff716d9eaf",
        image_uris: {
          small:
            "https://cards.scryfall.io/small/back/a/2/a2c044c0-3625-4bdf-9445-b462394cecae.jpg?1581395071",
          normal:
            "https://cards.scryfall.io/normal/back/a/2/a2c044c0-3625-4bdf-9445-b462394cecae.jpg?1581395071",
          large:
            "https://cards.scryfall.io/large/back/a/2/a2c044c0-3625-4bdf-9445-b462394cecae.jpg?1581395071",
          png: "https://cards.scryfall.io/png/back/a/2/a2c044c0-3625-4bdf-9445-b462394cecae.png?1581395071",
          art_crop:
            "https://cards.scryfall.io/art_crop/back/a/2/a2c044c0-3625-4bdf-9445-b462394cecae.jpg?1581395071",
          border_crop:
            "https://cards.scryfall.io/border_crop/back/a/2/a2c044c0-3625-4bdf-9445-b462394cecae.jpg?1581395071",
        },
      },
    ],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "not_legal",
      gladiator: "not_legal",
      pioneer: "not_legal",
      explorer: "not_legal",
      modern: "legal",
      legacy: "legal",
      pauper: "not_legal",
      vintage: "legal",
      penny: "legal",
      commander: "legal",
      oathbreaker: "legal",
      brawl: "not_legal",
      historicbrawl: "not_legal",
      alchemy: "not_legal",
      paupercommander: "restricted",
      duel: "legal",
      oldschool: "not_legal",
      premodern: "not_legal",
      predh: "not_legal",
    },
    games: ["paper", "mtgo"],
    reserved: false,
    foil: true,
    nonfoil: true,
    finishes: ["nonfoil", "foil"],
    oversized: false,
    promo: false,
    reprint: false,
    variation: false,
    set_id: "8052750a-aaf2-46fc-b46d-633f14124017",
    set: "dka",
    set_name: "Dark Ascension",
    set_type: "expansion",
    set_uri:
      "https://api.scryfall.com/sets/8052750a-aaf2-46fc-b46d-633f14124017",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3Adka&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/dka?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/a2c044c0-3625-4bdf-9445-b462394cecae/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A52adc761-1a0a-43d1-a706-41a92bb7880c&unique=prints",
    collector_number: "81",
    digital: false,
    rarity: "uncommon",
    artist: "David Palumbo",
    artist_ids: ["04ce1c75-e30c-4b7a-8cb0-b53e4ecc2f39"],
    border_color: "black",
    frame: "2003",
    frame_effects: ["sunmoondfc"],
    full_art: false,
    textless: false,
    booster: true,
    story_spotlight: false,
    edhrec_rank: 7898,
    penny_rank: 13984,
    prices: {
      usd: "0.21",
      usd_foil: "4.69",
      usd_etched: null,
      eur: "0.24",
      eur_foil: "0.80",
      tix: "0.02",
    },
    related_uris: {
      gatherer:
        "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=262675",
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Afflicted+Deserter+%2F%2F+Werewolf+Ransacker&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Afflicted+Deserter+%2F%2F+Werewolf+Ransacker&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=Afflicted+Deserter",
    },
    purchase_uris: {
      tcgplayer:
        "https://www.tcgplayer.com/product/57632?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      cardmarket:
        "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Afflicted+Deserter&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
      cardhoarder:
        "https://www.cardhoarder.com/cards/43329?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
    },
  },
];
